language: node_js
cache:
  directories:
    - node_modules
os:
  - linux
  - osx
before_install:
  - npm install -g --no-progress npm@5.5.1
install:
  - npm install --no-progress
script:
  - npm test -- -R dot --check-leaks
